name: test

on: [ push, pull_request ]

env:
  POKY_BRANCH: honister

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: mkdir build
      - run: chmod +x sources/prepare-yocto.sh
      - run: docker compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g) rpi-image-build
      - run: docker compose run rpi-image-build
